[[redirects]]
  from = "/api/*"
  to = "https://holdemserver-1dfb99f436f4.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://holdemserver-1dfb99f436f4.herokuapp.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/request/*"
  to = "https://holdemserver-1dfb99f436f4.herokuapp.com/request/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/employees/*"
  to = "https://holdemserver-1dfb99f436f4.herokuapp.com/employees/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tsheet/*"
  to = "https://holdemserver-1dfb99f436f4.herokuapp.com/tsheet/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://holdemserver-1dfb99f436f4.herokuapp.com/:splat"
  status = 200
  force = true